config/routes.rb
Rails.application.routes.draw do
  resources :entries

  devise_for :users
  root 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get '/donate' => 'static_pages#donate'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :user

	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
			:recoverable, :rememberable, :trackable, :validatable
	has_many :entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
	before_filter :configure_permitted_parameters, if: :devise_controller?
	protect_from_forgery with: :exception
	protected
	def configure_permitted_parameters
   	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
	end

	def after_sign_in_path_for(resource)
		entries_path
	end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	before_action :set_entry, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!

	respond_to :html

	def index
		@entries = current_user.entries.paginate(:page => params[:page], :per_page => 25)
		respond_with(@entries)
	end

	def show
		respond_with(@entry)
	end

	def new
		@entry = Entry.new
		respond_with(@entry)
	end

	def edit
	end

	def create
		@entry = current_user.entries.create(entry_params)
		if @entry.save
			flash[:notice] = "Entry saved!"
		else
			flash[:alert] = "Entry not saved!"
		end
		respond_with(@entry)
	end

	def update
		@entry.update(entry_params)
		respond_with(@entry)
	end

	def destroy
		@entry.destroy
		respond_with(@entry)
	end

	private
		def set_entry
			@entry = current_user.entries.find_by(id: params[:id])
		end

		def entry_params
			params.require(:entry).permit(:title, :content)
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def about
	end

	def contact
	end

	def donate
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
	def formatDate(date)
		"#{date.month}/#{date.day}/#{date.year}"
	end

	def html_format(entry)
		entry.gsub('<', '&lt').gsub('>', '&gt').gsub("\n", '<br />').html_safe
	end
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
	<% if @entry.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

			<ul>
			<% @entry.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :title %><br>
		<%= f.text_field :title, class: "form-control" %>
	</div>
	<div class="field">
		<%= f.label :content %><br>
		<%= f.text_area :content, class: "form-control entry-content" %>
	</div><br>
	<div class="actions">
		<%= f.submit class: "btn btn-primary" %>
	</div>
<% end %>

app/views/entries/edit.html.erb
<% provide :title, "Editing Entry" %>
<h1>Editing Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<% provide :title, "Your entries" %>
<% former_day = nil %>

<%= link_to "New entry", new_entry_path, class: "btn btn-primary pull-right", style: "margin-top: 20px;" %>

<% if @entries.empty? %>
<h1>
	You have no entries! <%= link_to "Make some!", new_entry_path %>
</h1>
<% end %>

<% @entries.reverse.each do |entry| %>
	<% if former_day != formatDate(entry.created_at) %>
<h2 class="date">
	<%= formatDate(entry.created_at) %>
</h2>
	<% end %>
	
	<% if entry.title.nil? or entry.title == "" %>
<%= link_to "Untitled Entry", entry, class: "btn btn-default" %>
	<% else %>
<%= link_to entry.title, entry, class: "btn btn-default" %>
	<% end %>
<% former_day = formatDate(entry.created_at) %>
<% end %>

<%= will_paginate @entries, renderer: BootstrapPagination::Rails %>

app/views/entries/new.html.erb
<% provide :title, "New Entry" %>
<h1>New Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<% provide :title, @entry.title %>
<h1>
  <%= @entry.title %>
</h1>

<p>
  <%= html_format(@entry.content) %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Nightbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<%= render 'layouts/partials/header' %>

<% if alert != nil or notice != nil %>
<div class="container">
	<% if alert != nil %>
	<p class="alert bg-danger"><%= alert %> <a href="#"><span class="glyphicon glyphicon-remove-sign" style="float: right; top: 4px;" onclick="$('.alert').slideUp();"> </span></a></p>
	<% end %>
	<% if notice != nil %>
	<p class="notice bg-success"><%= notice %> <a href="#"><span class="glyphicon glyphicon-remove-sign" style="float: right; top: 4px;" onclick="$('.notice').slideUp();"> </span></a></p>
	<% end %>
</div>
<% end %>
<% if yield(:override) == "" or yield(:override) == false %>
<div class="container main-container">
	<%= yield %>
</div>
<% else %>
<%= yield %>
<% end %>

<%= render 'layouts/partials/footer' %>

</body>
</html>

app/views/layouts/partials/_bs_header.html.erb
<div class="navbar navbar-inverse">
	<div class="container-fluid">
		
		<div class="navbar-header">
			<button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nb-navbar-collapse-1" type="button">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "NightBook", root_path, class: 'navbar-brand' %>
		</div>

		<div class="collapse navbar-collapse" id="nb-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li>
					<%= link_to "Home", root_path %>
				</li>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/partials/_footer.html.erb
<div class="container">
	<footer>
		<hr>
		<ul class="pull-left">
			<li>
				<%= link_to "Home", root_path %>
			</li>
			<li>
				<%= link_to "About", about_path %>
			</li>
			<li>
				<%= link_to "Contact", contact_path %>
			</li>
			<li>
				<%= link_to "Donate", donate_path %>
			</li>
		</ul>

		<div class="pull-right">
			Copyright &copy;2016 Mark Rawls
		</div>
	</footer>
</div>

app/views/layouts/partials/_header.html.erb
<script type="text/javascript">
$(document).ready(function() {
	$("#current-account").hover(function() {
		$("#current-account").addClass("active");
		$("#user-menu").removeClass("hidden");
	}, function() {
		$("#current-account").removeClass("active");
		$("#user-menu").addClass("hidden");
	});
	$("#user-menu").hover(function() {
		$("#current-account").addClass("active");
		$("#user-menu").removeClass("hidden");
	}, function() {
		$("#current-account").removeClass("active");
		$("#user-menu").addClass("hidden");
	});
});
</script>
<div class="main-header">
	<%= link_to(root_path) do %>
	<%= image_tag("nightbook_logo.png", :class => "header-image") %>
	<% end %>

	<%= link_to(root_path) do %>
	<div class="header-unit">
		Home
	</div>
	<% end %>

	<%= link_to(about_path) do %>
	<div class="header-unit">
		About
	</div>
	<% end %>

	<% if user_signed_in? %>
	<%= link_to entries_path do %>
	<div class="header-unit pull-right" id="current-account">
		<%= current_user.name %>
	</div>
	<% end %>
	<% else %>
	<%= link_to(new_user_session_path) do %>
	<div class="header-unit pull-right">
		Log In
	</div>
	<% end %>
	<% end %>
</div>

<div id="user-menu" class="hidden">
	<ul>
		<%= link_to entries_path do %>
		<li>
			<span class="glyphicon glyphicon-book"></span> My Entries
		</li>
		<% end %>
		<%= link_to new_entry_path do %>
		<li>
			<span class="glyphicon glyphicon-file"></span> New Entry
		</li>
		<% end %>
		<%= link_to destroy_user_session_path, :method => :delete do %>
		<li>
			<span class="glyphicon glyphicon-log-out"></span> Log Out
		</li>
		<% end %>
	</ul>
</div>

app/views/static_pages/about.html.erb
<% provide :title, "About" %>
<div style="height: 20px; width: 100%;"></div>
<div class="row">
	<div class="col-md-12">
		<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
			<div class="panel panel-default">
				<div class="panel-heading" id="headingOne" role="tab">
					<h4 class="panel-title">
						<a href="#collapseOne" data-toggle="collapse" data-parent="accordion" aria-expanded="true" aria-controls="collapseOne">
							What is NightBook?
						</a>
					</h4>
				</div>

				<div class="panel-collapse collapse in" id="collapseOne" role="tabpanel" aria-labelledby="headingOne">
					<div class="panel-body">
						NightBook is an online journaling application. Which, generally speaking, is pretty awesome. NightBook uses powerful encryption and multifaceted authentication to help protect your secrets, so you are welcome to write whatever you want. Not even our systems administrators can view it. Your secrets are kept between you and whoever you choose to share them with.
					</div>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading" id="headingTwo" role="tab">
					<h4 class="panel-title">
						<a href="#collapseTwo" data-toggle="collapse" data-parent="accordion" aria-expanded="false" aria-controls="collapseTwo">
							How do I share my entries?
						</a>
					</h4>
				</div>

				<div class="panel-collapse collapse" id="collapseTwo" role="tabpanel" aria-labelledby="headingTwo">
					<div class="panel-body">
						Well, either copy and paste it, or show somebody on your device. Beyond that, NightBook does not support sharing. We likely never will. This is to prevent your sensitive information from being shared with anybody that you might not want to see it. Your personal NightBook is your business, and we feel that it should always stay that way. We want you to be able to write anything you want without fear of others.
					</div>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading" id="headingThree" role="tab">
					<h4 class="panel-title">
						<a href="#collapseThree" data-toggle="collapse" data-parent="accordion" aria-expanded="false" aria-controls="collapseThree">
							Can I write about {x}?
						</a>
					</h4>
				</div>

				<div class="panel-collapse collapse" id="collapseThree" role="tabpanel" aria-labelledby="headingThree">
					<div class="panel-body">
						Sure. Write about whatever makes you happy. Or sad. Or angry. Write a novel - there's no character limit on your NightBook entries. Keep in mind, your entry content will not paginate, so if you write a novel, expect it all on one page if you put it all in one entry. Write safely knowing that nobody can ever find your entries.
					</div>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading" id="headingFour" role="tab">
					<h4 class="panel-title">
						<a href="#collapseFour" data-toggle="collapse" data-parent="accordion" aria-expanded="false" aria-controls="collapseFour">
							Privacy Policy (Simplified)
						</a>
					</h4>
				</div>

				<div class="panel-collapse collapse" id="collapseFour" role="tabpanel" aria-labelledby="headingFour">
					<div class="panel-body">
						We will never, under any circumstances sell or otherwise give your information to anybody, to the extent of the law. When we receive your personal information (Email address and first name supplied in sign up process), that is never used for any reason beyond signing in. Your information is protected to the best of our abilities, and our privacy policy is readily available. By using this website, you agree to the terms of service and to our privacy policy.
					</div>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading" id="headingFive" role="tab">
					<h4 class="panel-title">
						<a href="#collapseFive" data-toggle="collapse" data-parent="accordion" aria-expanded="false" aria-controls="collapseFive">
							Terms of Service/Privacy Policy
						</a>
					</h4>
				</div>

				<div class="panel-collapse collapse" id="collapseFive" role="tabpanel" aria-labelledby="headingFive">
					<div class="panel-body">
						<h2>
							Web Site Terms and Conditions of Use
						</h2>

						<h3>
							1. Terms
						</h3>

						<p>
							By accessing this web site, you are agreeing to be bound by these 
							web site Terms and Conditions of Use, all applicable laws and regulations, 
							and agree that you are responsible for compliance with any applicable local 
							laws. If you do not agree with any of these terms, you are prohibited from 
							using or accessing this site. The materials contained in this web site are 
							protected by applicable copyright and trade mark law.
						</p>

						<h3>
							2. Use License
						</h3>

						<ol type="a">
							<li>
								Permission is granted to temporarily download one copy of the materials 
								(information or software) on NightBook's web site for personal, 
								non-commercial transitory viewing only. This is the grant of a license, 
								not a transfer of title, and under this license you may not:
								
								<ol type="i">
									<li>modify or copy the materials;</li>
									<li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
									<li>attempt to decompile or reverse engineer any software contained on NightBook's web site;</li>
									<li>remove any copyright or other proprietary notations from the materials; or</li>
									<li>transfer the materials to another person or "mirror" the materials on any other server.</li>
								</ol>
							</li>
							<li>
								This license shall automatically terminate if you violate any of these restrictions and may be terminated by NightBook at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
							</li>
						</ol>

						<h3>
							3. Disclaimer
						</h3>

						<ol type="a">
							<li>
								The materials on NightBook's web site are provided "as is". NightBook makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, NightBook does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
							</li>
						</ol>

						<h3>
							4. Limitations
						</h3>

						<p>
							In no event shall NightBook or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on NightBook's Internet site, even if NightBook or a NightBook authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
						</p>
									
						<h3>
							5. Revisions and Errata
						</h3>

						<p>
							The materials appearing on NightBook's web site could include technical, typographical, or photographic errors. NightBook does not warrant that any of the materials on its web site are accurate, complete, or current. NightBook may make changes to the materials contained on its web site at any time without notice. NightBook does not, however, make any commitment to update the materials.
						</p>

						<h3>
							6. Links
						</h3>

						<p>
							NightBook has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by NightBook of the site. Use of any such linked web site is at the user's own risk.
						</p>

						<h3>
							7. Site Terms of Use Modifications
						</h3>

						<p>
							NightBook may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.
						</p>

						<h3>
							8. Governing Law
						</h3>

						<p>
							Any claim relating to NightBook's web site shall be governed by the laws of the State of Florida without regard to its conflict of law provisions.
						</p>

						<p>
							General Terms and Conditions applicable to Use of a Web Site.
						</p>



						<h2>
							Privacy Policy
						</h2>

						<p>
							Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.
						</p>

						<ul>
							<li>
								Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
							</li>
							<li>
								We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.		
							</li>
							<li>
								We will only retain personal information as long as necessary for the fulfillment of those purposes. 
							</li>
							<li>
								We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned. 
							</li>
							<li>
								Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date. 
							</li>
							<li>
								We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
							</li>
							<li>
								We will make readily available to customers information about our policies and practices relating to the management of personal information. 
							</li>
						</ul>

						<p>
							We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained. 
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/contact.html.erb
<% provide :title, "Contact" %>
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1>Contact us</h1>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<p class="lead">Send me an email at <a href="mailto:mark@quantumsoftware.org">mark@quantumsoftware.org</a> and I will get back with you as soon as a possible.</p>
	</div>
</div>

app/views/static_pages/donate.html.erb
<% provide :title, "Donate" %>

<div class="row">
	<div class="col-md-12">
		<h1 style="text-align: center;">Why donate?</h1>
	</div>
</div>

<div class="row">
	<div class="col-md-4 triplet">
		<h3>Coffee isn't cheap</h3>
		<p>
			Seriously. NightBook is a one-man project, and it's hard to code all of the wonderful goodies that you all love without some major caffeine going on. Just $2 makes a huge difference in my coffee <s>addiction</s> budget.
		</p>
	</div>

	<div class="col-md-4 triplet">
		<h3>Neither is college</h3>
		<p>
			I'm going to school full time for an absolutely massive list of reasons, and I'm struggling a lot with tuition. My day job just isn't cutting it, and web design work is infrequent at best. Any amount at all would help greatly.
		</p>
	</div>

	<div class="col-md-4 triplet">
		<h3>Get your name on a list</h3>
		<p>
			If you donate and forward me a copy of your receipt through <%= link_to "Email", contact_path %>, I'll take your name and a brief tagline that you write and stick on a big list for the whole world to see. Each donor of $10+ also gets three days up on the front page, with whatever information they want to put.
		</p>
	</div>
</div>

<div class="row">
	<div class="col-md-4 triplet"></div>
	<div class="col-md-4 triplet"><%= donate_button %></div>
	<div class="col-md-4 triplet"></div>
</div>

app/views/static_pages/home.html.erb
<% provide :title, "Home" %>
<% provide :override, true %>
<script type="text/javascript">
$(document).ready(function() {
	$("#header-carousel").owlCarousel({
		lazyLoad : true,
		slideSpeed : 300,
		paginationSpeed : 100,
		singleItem : true,
		pagination : false,
		autoPlay : 8000,
	});
});
</script>

<div id="header-carousel" class="owl-carousel owl-theme">
	<div class="item">
		<div class="jumbotron">
			<div class="container">
				<img class="lazyOwl" data-src="<%= asset_url('purple_book_icon.png') %>" alt="Book icon" width="256" height="256" />

				<h1>
					What is NightBook?
				</h1>

				<p>
					NightBook is a way for you to privately host your own diary. Never worry about anybody going through your private journal - your secrets are safe with us.
				</p>

				<br>

				<%= link_to "Learn more!", about_path, class: "btn btn-primary btn-lg", style: "clear: right;" %>
			</div>
		</div>
	</div>
	<div class="item">
		<div class="jumbotron">
			<div class="container">
				<h1>
					Oh cool! But what if I want to share with my friends?
				</h1>

				<p>
					Then you go make a <a href="http://facebook.com/">Facebook</a> or a <a href="http://tumblr.com/">Tumblr</a> or something. We will never, ever share any of your posts for any reason.
				</p>

				<p>Your privacy is our business.</p>

				<%= link_to "Learn yet more!", about_path, class: "btn btn-primary btn-lg", style: "clear: right;" %>
			</div>
		</div>
	</div>
	<div class="item">
		<div class="jumbotron">
			<div class="container">
				<h1>
					Radical! Where do I sign up?
				</h1>

				<p>
					I'm so glad that you've decided to keep your journal with us. I'll go prepare a welcoming party, maybe bake a cake or something. You like cake, right? Sweet, sweet cake.
				</p>

				<p>
					<%= link_to "Sign up now", new_user_registration_path, class: "btn btn-primary btn-lg" %>
				</p>
			</div>
		</div>
	</div>
</div>

<div class="container main-container">
	<div class="row">
		<div class="col-md-4 triplet">
			<h3>
				Totally free.
			</h3>
			<p>
				And we mean it. NightBook will never ask for your credit card. No premium memberships, no special treatment. We survive on your donations, but this is the only place that we will even ask.
			</p>
		</div>
		<div class="col-md-4 triplet">
			<h3>
				Totally private.
			</h3>
			<p>
				We store your journals in a heavily encrypted database, and we will never give up any of your information for any reason. The only person that ever sees your writing is you.
			</p>
		</div>
		<div class="col-md-4 triplet">
			<h3>
				Totally easy.
			</h3>
			<p>
				Just put down whatever you are thinking and hit save and our system will take care of the rest.
			</p>
		</div>
	</div>

	<div class="row">
		<div class="col-md-4 triplet">
			<%= link_to "Donate", donate_path, class: "btn btn-primary" %>
		</div>
		<div class="col-md-4 triplet">
			<%= link_to "Learn more", about_path, class: "btn btn-primary" %>
		</div>
		<div class="col-md-4 triplet">
			<%= link_to "Sign me up!", new_user_registration_path, class: "btn btn-primary" %>
		</div>
	</div>
</div>

<div class="container main-container">
	<div class="row">
		<div class="col-md-12">
			<h2>Don't just take it from me though, read these quotes from my favorite books!</h2>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<blockquote>
				<p>Even impaled on a spear, he was confident he could - suddenly he was impaled on a spear.</p>
				<footer>Ari Bach, author of <cite title="Ragnarok">Ragnarok</cite></footer>
			</blockquote>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<blockquote>
				<p>The ships hung in the sky much in the same way that bricks don't.</p>
				<footer>Douglas Adams, author of <cite title="The Hitchhiker's Guide to the Galaxy">The Hitchhiker's Guide to the Galaxy</cite></footer>
			</blockquote>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<blockquote>
				<p>Pelamus turned around, and bless the idiot, he gave a monologue.</p>
				<footer>Ari Bach, author of <cite title="Ragnarok">Ragnarok</cite></footer>
			</blockquote>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<blockquote>
				<p>"Hmmm, very severe... Poor condition, heavy infection... Disarticulation... Oh no, no... Clearly broken... Mm-hmmm... All right, then, all's well, perfect health, clear to go."</p>
				<footer>Dr. Niide, from <cite title="Valhalla">Valhalla</cite> by Ari Bach</footer>
			</blockquote>
		</div>
	</div>
</div>